#!/usr/bin/python3
import random

board = [' ' for x in range(10)]
letters = ['X', 'O']
player = random.choice(letters)
comp = ''

if player == 'X':
    comp = 'O'
else:
    comp = 'X'

def insertLetter(letter, pos):
    board[pos] = letter

def spaceIsFree(pos):
    return board[pos] == ' '

def printBoard(board):
    print(' ' + board[1] + ' | ' + board[2] + ' | ' + board[3])
    print('------------')
    print(' ' + board[4] + ' | ' + board[5] + ' | ' + board[6])
    print('------------')
    print(' ' + board[7] + ' | ' + board[8] + ' | ' + board[9])
    print()

def isWinner(board, letter):
    return (board[1] == letter and board[2] == letter and board[3] == letter) or (board[4] == letter and board[5] == letter and board[6] == letter) or  (board[7] == letter and board[8] == letter and board[9] == letter) or (board[1] == letter and board[4] == letter and board[7] == letter) or (board[2] == letter and board[5] == letter and board[8] == letter) or (board[3] == letter and board[6] == letter and board[9] == letter) or (board[1] == letter and board[5] == letter and board[9] == letter) or (board[3] == letter and board[5] == letter and board[7] == letter)


def playerMove():
    run = True
    while run:
        move = input(f'Select a position (1-9) to place an {player}: ')
        try:
            move = int(move)
            if move > 0 and move < 10:
                if spaceIsFree(move):
                    run = False
                    insertLetter(player, move)
                else:
                    print('Space already taken')
            else:
                print('Choose a number from 1 to 9')
        except:
            print("That's not a number. Choose a number from 1 to 9")

def compMove():
    possibleMoves = [x for x, letter in enumerate(board) if letter == ' ' and x != 0]
    move = 0

    for letter in ['O', 'X']:
        for i in possibleMoves:
            boardCopy = board[:]
            boardCopy[i] = letter
            if isWinner(boardCopy, letter):
                move = i
                return move

    cornersOpen = []
    for i in possibleMoves:
        if i in [1, 3, 7, 9]:
            cornersOpen.append(i)

    if len(cornersOpen) > 0:
        move = selectRandom(cornersOpen)
        return move

    if 5 in possibleMoves:
        move = 5
        return move

    centersOpen = []
    for i in possibleMoves:
        if i in [2, 4, 6, 8]:
            centersOpen.append(i)

    if len(centersOpen) > 0:
        move = selectRandom(centersOpen)
        return move

    return move

def selectRandom(li):
    ln = len(li)
    r = random.randrange(0, ln)
    return li[r]

def isBoardFull(board):
    if board.count(' ') > 1:
        return False
    else:
        return True

def main():
    printBoard(board)

    while not (isBoardFull(board)):
        if player == 'X':
            if not (isWinner(board, comp)):
                playerMove()
                printBoard(board)
            else:
                print(f'{comp} wins')
                break

            if not (isWinner(board, player)):
                move = compMove()
                if move == 0:
                    print('Catscratch')
                else:
                    insertLetter(comp, move)
                    printBoard(board)
            else:
                print(f'{player} wins')
                break
        else:
             if not (isWinner(board, player)):
                move = compMove()
                if move == 0:
                    print('Catscratch')
                else:
                    insertLetter(comp, move)
                    printBoard(board)
             else:
                 print(f'{player} wins')
                 break

             if not (isWinner(board, comp)):
                 playerMove()
                 printBoard(board)
             else:
                 print(f'{comp} wins')
                 break

    if isBoardFull(board):
        print('Catscratch')

if __name__ == '__main__':
    main()

    while True:
        res = input("Would you like to play again? ").strip().lower()
        if res == "yes" or res == "y":
            board = [' ' for x in range(10)]
            player = random.choice(letters)
            comp = ''

            if player == 'X':
                comp = 'O'
            else:
                comp = 'X'
            main()
        elif res == "no" or res == "n":
            break
        else:
            print("Type 'yes' or 'no'")

